//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ConfettiMachine.rc
//
#define IDR_MANIFEST                    1
#define IDD_ABOUTBOX                    100
#define IDD_CONFIGURATIONVIEW           104
#define IDR_MAINFRAME                   128
#define IDPP_PARTICLESYSTEM             132
#define IDPP_EMITTER                    134
#define IDD_NEWEMITTER                  135
#define IDPP_APPEARANCE                 136
#define IDPP_ENVIRONMENT                137
#define IDPP_BOUNCEPLANE                138
#define IDPP_CLIPPLANE                  139
#define IDD_NEWAPPEARANCE               140
#define IDD_NEWBOUNCEPLANE              141
#define IDD_NEWENVIRONMENT              143
#define IDD_NEWCLIPPLANE                144
#define IDC_CONTROLS_PARTICLESYSTEM_EMITTERS 1006
#define IDC_CONTROLS_ENVIRONMENT_CLIPPLANES 1008
#define IDC_CONTROLS_EMITTER_NEW        1009
#define IDC_CONTROLS_EMITTER_DELETE     1010
#define IDC_NEWEMITTER_NAME             1011
#define IDC_CONTROLS_EMITTER_NAME       1015
#define IDC_CONTROLS_EMITTER_VOLUME     1016
#define IDC_CONTROLS_EMITTER_APPEARANCE 1017
#define IDC_CONTROLS_EMITTER_ENVIRONMENT 1018
#define IDC_CONTROLS_EMITTER_PARTICLETYPE_POINT 1019
#define IDC_CONTROLS_EMITTER_PARTICLETYPE_STREAK 1020
#define IDC_CONTROLS_EMITTER_PARTICLETYPE_TEXTURED 1021
#define IDC_CONTROLS_EMITTER_PARTICLETYPE_SPHERE 1022
#define IDC_CONTROLS_EMITTER_PARTICLETYPE_EMITTER 1023
#define IDC_CONTROLS_EMITTER_COUNT      1024
#define IDC_CONTROLS_EMITTER_LIFETIME   1025
#define IDC_CONTROLS_PARTICLESYSTEM_RESTART 1025
#define IDC_CONTROLS_EMITTER_INITIALCOLOR 1026
#define IDC_CONTROLS_APPEARANCE_NAME    1026
#define IDC_CONTROLS_EMITTER_MAXVELOCITY 1027
#define IDC_CONTROLS_APPEARANCE_NEW     1027
#define IDC_CONTROLS_EMITTER_MINVELOCITY 1028
#define IDC_CONTROLS_APPEARANCE_DELETE  1028
#define IDC_CONTROLS_EMITTER_INITIALRADIUS 1029
#define IDC_CONTROLS_ENVIRONMENT_NAME   1029
#define IDC_CONTROLS_EMITTER_MAXSPREAD  1030
#define IDC_CONTROLS_ENVIRONMENT_NEW    1030
#define IDC_CONTROLS_ENVIRONMENT_DELETE 1031
#define IDC_CONTROLS_APPEARANCE_RADIUSRATE 1032
#define IDC_CONTROLS_APPEARANCE_COLORRATE_A 1033
#define IDC_CONTROLS_ENVIRONMENT_GRAVITY_X 1033
#define IDC_CONTROLS_APPEARANCE_ANGULARVELOCITY 1034
#define IDC_CONTROLS_ENVIRONMENT_BOUNCEPLANES 1034
#define IDC_CONTROLS_APPEARANCE_SIZE    1035
#define IDC_CONTROLS_BOUNCEPLANE_NAME   1035
#define IDC_CONTROLS_APPEARANCE_TEXTURE 1036
#define IDC_CONTROLS_BOUNCEPLANE_NEW    1036
#define IDC_CONTROLS_APPEARANCE_COLORRATE_B 1037
#define IDC_CONTROLS_BOUNCEPLANE_DELETE 1037
#define IDC_CONTROLS_APPEARANCE_COLORRATE_G 1038
#define IDC_CONTROLS_CLIPPLANE_NAME     1038
#define IDC_CONTROLS_APPEARANCE_COLORRATE_R 1039
#define IDC_CONTROLS_CLIPPLANE_NEW      1039
#define IDC_CONTROLS_ENVIRONMENT_GRAVITY_Y 1040
#define IDC_CONTROLS_ENVIRONMENT_GRAVITY_Z 1041
#define IDC_CONTROLS_ENVIRONMENT_WINDVELOCITY_X 1042
#define IDC_CONTROLS_ENVIRONMENT_WINDVELOCITY_Y 1043
#define IDC_CONTROLS_ENVIRONMENT_WINDVELOCITY_Z 1044
#define IDC_CONTROLS_ENVIRONMENT_GUSTINESS_X 1045
#define IDC_CONTROLS_ENVIRONMENT_GUSTINESS_Y 1046
#define IDC_CONTROLS_ENVIRONMENT_GUSTINESS_Z 1047
#define IDC_CONTROLS_CLIPPLANE_DELETE   1048
#define IDC_CONTROLS_CLIPPLANE_X        1049
#define IDC_CONTROLS_CLIPPLANE_Y        1050
#define IDC_CONTROLS_CLIPPLANE_Z        1051
#define IDC_CONTROLS_CLIPPLANE_D        1052
#define IDC_CONTROLS_BOUNCEPLANE_X      1053
#define IDC_CONTROLS_ENVIRONMENT_AIRFRICTION 1054
#define IDC_CONTROLS_BOUNCEPLANE_Y      1054
#define IDC_CONTROLS_BOUNCEPLANE_Z      1055
#define IDC_CONTROLS_BOUNCEPLANE_D      1056
#define IDC_CONTROLS_BOUNCEPLANE_DAMPENING 1057
#define IDC_NEWAPPEARANCE_NAME          1059
#define IDC_NEWBOUNCEPLANE_NAME         1060
#define IDC_CLIPPLANE_NAME              1061
#define IDC_NEWENVIRONMENT_NAME         1062
#define IDC_NEWCLIPPLANE_NAME           1063

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
